#!/usr/bin/env bash

# from version:
#  Redis server v=8.8.2 sha=c5031f43:1 malloc=jemalloc-5.3.0 build=d11a7d72746205e6

podman build --platform linux/amd64,linux/arm64 \
  . -f "./Dockerfile" \
  --manifest "us-docker.pkg.dev/uwit-mci-iam/containers/redis:8.8.2"

