#!/usr/bin/env bash

# from version:
#  Redis server v=8.10.1 sha=3399357e:1 malloc=jemalloc-5.3.0 build=4fa656f8bd822b64

podman build --platform linux/amd64,linux/arm64 \
  . -f "./Dockerfile" \
  --manifest "us-docker.pkg.dev/uwit-mci-iam/containers/redis:8.10.1"

