#!/usr/bin/env bash

# from version:
#   mariadbd  Ver 13.0.1-MariaDB for Linux on x86_64 (MariaDB Server)

podman build --platform linux/amd64,linux/arm64 \
  . -f "./Dockerfile" \
  --manifest "us-docker.pkg.dev/uwit-mci-iam/containers/mariadb:13.0.1"

