name: "Testing multi-arch Docker builds"

on:
  workflow_dispatch:

jobs:
  task:
    strategy:
      matrix:
        py_version:
          - "3.9"

    permissions:
      contents: write
      pull-requests: write
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Cloud
        uses: 'uwit-iam/action-auth-artifact-registry@main'
        with:
          credentials: "${{ secrets.MCI_GCLOUD_AUTH_JSON }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push somewhere
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:images/python-base"
          platforms: linux/amd64,linux/arm64
          build-args: PYTHON_VERSION=${{ matrix.py_version }}
          push: true
          tags: kevintest:latest
