name: "Testing multi-arch Docker builds"

on:
  workflow_dispatch:

jobs:
  task:
    permissions:
      contents: write
      pull-requests: write
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Cloud
        uses: 'uwit-iam/action-auth-artifact-registry@main'
        with:
          credentials: "${{ secrets.MCI_GCLOUD_AUTH_JSON }}"

      - name: Build and push somewhere
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kevintest:latest
