name: "Run 'poetry update' and create a PR"

on:
  push:
    branches:
      - run-poetry-update-workflow
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  task:
    permissions:
      contents: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abatilo/actions-poetry@v2.1.3
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ::set-output name=build-id::$(date +'%Y.%m.%dT%H%M%S')
        id: configure
      - run: |
          cd images/uw-saml-poetry
          poetry update --lock
        id: poetry-update
      - uses: ./.github/actions/build-library-image
        with:
          build_id: ${{ steps.configure.outputs.build-id }}
          image_name: poetry
        name: Re-build poetry base image
      - uses: ./.github/actions/build-library-image
        with:
          build_id: ${{ steps.configure.outputs.build-id }}
          image_name: uw-saml-poetry
          from_base_tag: ${{ steps.configure.outputs.build-id }}
        name: Re-build uw-saml-poetry image
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          add-paths: images/uw-saml-poetry/poetry.lock
          commit-message: ${{ env.message }}
          delete-branch: true
          title: ${{ env.message }}
          assignees: tomthorogood
          reviewers: tomthorogood
        env:
          message: >
            [github actions] poetry update
            (build-id: ${{ steps.configure.outputs.build-id }})
