on:
  push:
    paths:
      - images/uw-saml-poetry/**
      - images/uw-saml-poetry.dockerfile
      - .github/workflows/release-uw-saml-poetry-image.yml
  schedule:
    # Run at 2:15am every Monday.
    # Because this depends on the poetry image, we run this a few minutes later
    # so that it gets updated with the freshest version.
    - cron: '15 2 * * 1'
  workflow_dispatch:


jobs:
  release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dry-run'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/publish-release
        with:
          image: uw-saml-poetry
          dry-run: ${{ github.ref == 'refs/heads/dry-run'  && 'true' || 'false' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gcloud-token: ${{ secrets.GCR_TOKEN }}
          slack-token: ${{ secrets.ACTIONS_SLACK_BOT_TOKEN }}
