name: Update images
on:
  push:
  schedule:
    - cron: '0 2 * * 1'  # Run at 2am every Monday.

env:
  EDGE_TAG: latest
  DRY_RUN: ${{  github.event != 'schedule' }}

jobs:
  update-images:
    runs-on: ubuntu-latest
    name: Update image library
    steps:
      - uses: actions/checkout@v2
      - name: "Set VERSION"
        run: echo "VERSION=$(date +%Y.%-j.%-I.%-M)" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: update-image
        run: ./.github/update-image.sh -r poetry
      - name: Update uw-saml-poetry image
        run: ./.github/update-image.sh -r uw-saml-poetry
